### ISSUE TITLE
It does not work

### ISSUE THREAD

**Issue by 3kh0** [GDSlatherycGithub/meme2048#1]
I think a css file is missing...

![image](https://user-images.githubusercontent.com/58097612/150243652-ce5dacbe-0245-484d-a386-4d2b0c14455b.png)

**Comment by 3xionDev** [comment]
It's the fact that all the files are .zip files. My computer doesn't let me upload regular files to github, so I had to zip them. Unzip all the files into folders of the same name then upload them all into something like repl.it. It should work. Otherwise, you can just run the version I released on repl at meme2048.gdslatheryc.repl.co

**Comment by 3kh0** [comment]
ahhh i see
